// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnyJ9pjRypfJ3fsXOcm3UpR9cvXViKiZY',
    appId: '1:1003237536143:web:caab0157b921ad70c41bfa',
    messagingSenderId: '1003237536143',
    projectId: 'ecomersefirebase',
    authDomain: 'ecomersefirebase.firebaseapp.com',
    storageBucket: 'ecomersefirebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfeajxLNwXvOGxYJVEf4qjtUGg54XO55U',
    appId: '1:1003237536143:android:f0eafbf3d6f921d2c41bfa',
    messagingSenderId: '1003237536143',
    projectId: 'ecomersefirebase',
    storageBucket: 'ecomersefirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA10yuRhdTPrp7tCavLg3gbFbuWL2iGtPI',
    appId: '1:1003237536143:ios:25d978651b70644cc41bfa',
    messagingSenderId: '1003237536143',
    projectId: 'ecomersefirebase',
    storageBucket: 'ecomersefirebase.appspot.com',
    iosClientId: '1003237536143-4g90oanfrue54411vi334o4j90uig3lj.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA10yuRhdTPrp7tCavLg3gbFbuWL2iGtPI',
    appId: '1:1003237536143:ios:25d978651b70644cc41bfa',
    messagingSenderId: '1003237536143',
    projectId: 'ecomersefirebase',
    storageBucket: 'ecomersefirebase.appspot.com',
    iosClientId: '1003237536143-4g90oanfrue54411vi334o4j90uig3lj.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
